### PR TITLE
Added in healthcheck

### PR DESCRIPTION
**Pull request by rossdargan**
Added in a healthcheck to verify that the site is running correctly. Note this requires docker V 1.12.

### CODE REVIEW

**Comment by tyler43636** [comment]
@rossdargan I can't find anything in the Docker docs about what older versions of the engine do if the image has a health check defined. I primarily use this for my unraid server, which is far from Docker 1.12. Any links you can share about how older versions of Docker handle the HEALTHCHECK directive?

**Comment by rossdargan** [comment]
I tried in on 1.11 and it just said unknown command but didn't have an
issue with it when I built it. I can publish it to docker hub if you want
to try it on unraid?

I'm having issues where the site stops but the container doesn't terminate.
This would really help with that.

**Comment by tyler43636** [comment]
@rossdargan I've merged it. I have the same problem, but I've just been restarting it with a cron job. I'll ping you if the change ends up causing problems for me.

**Comment by rossdargan** [comment]
Thanks - I did a pull and this is working great for me. Hopefully it's working well for you to.

**Comment by tyler43636** [comment]
Everything is working for me too. Thanks for the help.

**Pull request merged**
